version: "3.8"

# Development overrides for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    volumes:
      - ./api:/app:cached
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm run dev
    stdin_open: true
    tty: true

  localai:
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./models:/models:cached
      - ./localai-data:/tmp/localai:cached

  postgres:
    environment:
      - POSTGRES_DB=llm_db_dev
    ports:
      - "5433:5432" # Different port for development
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  grafana:
    environment:
      - GF_LOG_LEVEL=debug
      - GF_INSTALL_PLUGINS=grafana-loki-datasource
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_dev_data:/var/lib/grafana

volumes:
  postgres_dev_data:
  grafana_dev_data:
