services:
  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  api:
    build: ./api
    environment:
      - LLM_BASE_URL=http://ollama:11434/v1
      - PORT=3000
    depends_on:
      - ollama
    ports:
      - "3000:3000"

volumes:
  ollama:
