services:
  ollama:
    image: ollama/ollama:latest
    platform: linux/amd64 # Use amd64 for better compatibility
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    image: ghcr.io/inderjotpujara/localai-privacy-api:latest
    environment:
      - LLM_BASE_URL=http://ollama:11434/v1
      - PORT=3000
    depends_on:
      - ollama
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3000/chat",
          "-X",
          "POST",
          "-H",
          "Content-Type: application/json",
          "-d",
          '{"model":"test","messages":[{"role":"user","content":"health"}],"max_tokens":1}',
        ]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s

volumes:
  ollama:
